name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # or your preferred Node.js version

      - name: Install dependencies
        run: npm i --force

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create .env file
        run: |
          echo "API_ACCESS_TOKEN=${{ secrets.API_ACCESS_TOKEN }}" >> .env
          echo "CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}" >> .env
          echo "VITE_API_URL=http://localhost:8000" >> .env

      - name: Use API Access Token
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
        run: echo "API token is set"

      - name: Use Claude API Key
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: echo "Claude API key is set"

      - name: Unit tests
        run: npx nx run-many -t test

      - name: Build
        run: npx nx build

      - name: E2E tests
        run: |
          npx nx serve context-gpt-backend &
          sleep 10 # Wait for the server to start
          npx nx run-many -t e2e

      - name: Lint
        run: npx nx run-many -t lint
